config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins_backoffice do
    # get 'admins/index'
    # get 'admins/edit/:id', to: 'admins#edit'
    get 'welcome/index' # Dashboard
    # resources :admins, only: [:index, :edit, :update, :new, :create ] #cria todas rotas padrão rest # Adms
    resources :admins #cria todas rotas padrão rest # Adms
    resources :subjects #cria todas rotas padrão rest # Assuntos
    resources :questions #cria todas rotas padrão rest # Questões
  end

  namespace :site do
    get 'welcome/index'
  end

  namespace :users_backoffice do
    get 'welcome/index'
  end

  devise_for :admins
  devise_for :users
  get 'inicio',to: 'site/welcome#index' 
  root  to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  paginates_per 5
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, inverse_of: :questions
  has_many :answers

  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController

  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit,:update, :destroy]

  def new 
    @admin =  Admin.new
  end

  def index
    @admins = Admin.all.page( params[:page])
  end

  def create
    @admin =  Admin.new(params_admin)

    if @admin.save()
      redirect_to admins_backoffice_admins_path, notice: "Administrador #{@admin.email} cadastrado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update     
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Administrador #{@admin.email} atualizado com sucesso!"
    else
      render :edit
    end
  end


  def destroy
    if @admin.destroy()
      redirect_to admins_backoffice_admins_path, notice: "Administrador #{@admin.email} excluído com sucesso!"
    else
      render :index
    end
  end

  private 

  def verify_password
    if( params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?)
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

  def set_admin
    @admin = Admin.find(params[:id]) 
  end

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
    before_action :set_question, only: [:edit, :update, :destroy]
    before_action :get_subjects, only: [:edit, :new]
  
    def new 
      @question =  Question.new
    end
  
    def index
      @questions = Question.includes(:subject)
                           .order(:description)
                           .page(params[:page])
    end
  
    def create
      @question =  Question.new(params_question)
  
      if @question.save()
        redirect_to admins_backoffice_questions_path, notice: "Questão #{@question.description} cadastrado com sucesso!"
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update     
      if @question.update(params_question)
        redirect_to admins_backoffice_questions_path, notice: "Questão #{@question.description} atualizado com sucesso!"
      else
        render :edit
      end
    end
  
  
    def destroy
      if @question.destroy()
        redirect_to admins_backoffice_questions_path, notice: "Questão #{@question.description} excluído com sucesso!"
      else
        render :index
      end
    end
  
    private 
    
    def get_subjects
      @subjects = Subject.all
    end

    def set_question
      @question = Question.find(params[:id]) 
    end
  
    def params_question
      params.require(:question).permit(:description,:subject_id, 
        answers_attributes: [:id, :description, :correct, :_destroy])
    end
  end
  

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
    before_action :set_subject, only: [:edit,:update, :destroy]
  
    def new 
      @subject =  Subject.new
    end
  
    def index
      @subjects = Subject.all.order(:description).page( params[:page])
    end
  
    def create
      @subject =  Subject.new(params_subject)
  
      if @subject.save()
        redirect_to admins_backoffice_subjects_path, notice: "Assunto #{@subject.description} cadastrado com sucesso!"
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update     
      if @subject.update(params_subject)
        redirect_to admins_backoffice_subjects_path, notice: "Assunto #{@subject.description} atualizado com sucesso!"
      else
        render :edit
      end
    end
  
  
    def destroy
      if @subject.destroy()
        redirect_to admins_backoffice_subjects_path, notice: "Assunto #{@subject.description} excluído com sucesso!"
      else
        render :index
      end
    end
  
    private 
  
    def set_subject
      @subject = Subject.find(params[:id]) 
    end
  
    def params_subject
      params.require(:subject).permit(:description)
    end
  end
  

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  
  
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!

    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    layout :layout_by_resource

    protected

    def layout_by_resource
        if devise_controller? && resource_class = "Admin"
            "admin_devise"
        else
            "application"
        end
    end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController

    def index
    end

end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper

    def translate_attr(object = nil, attr = nil)    
        (object && attr) ? object.human_attribute_name(attr) : "Informe os parametros corretamente" 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/questions/_answer_fields.html.erb
<div class="nested-fields">
    <%= f.label :description %> </br>
    <%= f.text_field :description %>
    <%= f.check_box :correct %> Correta?

    <%= link_to_remove_association('Remover', f) %>
</div>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
           locals: { action_message: 'Editando' }%>

app/views/admins_backoffice/questions/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= t('messages.listing',model: @questions.model_name.human(count: 2))%></h1>
    </div>
</div>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th><%= translate_attr(@questions,:description)%></th>
            <th><%= translate_attr(@questions,:subject)%></th>
            <th>            
                <%= link_to new_admins_backoffice_question_path, class:"btn btn-success btn-circle" do %>
                    <i class="fa fa-plus"></i>
                <% end %>
            </th>
        </tr>
    </thead>
    <tbody>
        <% @questions.each do |question| %>
            <tr>
                <td><%= question.id%></td>
                <td><%= question.description.truncate(50)%></td>
                <td><%= question.subject.description.truncate(30)%></td>
                <td style="width: 200px">

                    <%= link_to edit_admins_backoffice_question_path(question), class:"btn btn-primary btn-circle" do %>
                        <i class="fa fa-edit"></i>
                    <% end %>

                    <%= link_to admins_backoffice_question_path(question),
                                method: :delete, class:"btn btn-danger btn-circle", 
                                data: { confirm: t('messages.confirm_with', item: question.description.truncate(15))} do %>
                        <i class="fa fa-minus"></i>
                    <% end %>


                </td>
            </tr>
        <% end%>
    </tbody>
   
</table>

<div class="text-center"> 
    <%=  paginate @questions%>
</div>

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
           locals: { action_message: 'Novo' }%>

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: { action_message: 'Editando' }%>

app/views/admins_backoffice/subjects/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= t('messages.listing',model: @subjects.model_name.human(count: 2))%></h1>
    </div>
</div>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th><%= translate_attr(@subjects,:description)%></th>
            <th>            
                <%= link_to new_admins_backoffice_subject_path, class:"btn btn-success btn-circle" do %>
                    <i class="fa fa-plus"></i>
                <% end %>
            </th>
        </tr>
    </thead>
    <tbody>
        <% @subjects.each do |subject| %>
            <tr>
                <td><%= subject.id%></td>
                <td><%= subject.description%></td>
                <td style="width: 200px">

                    <%= link_to edit_admins_backoffice_subject_path(subject), class:"btn btn-primary btn-circle" do %>
                        <i class="fa fa-edit"></i>
                    <% end %>

                    <%= link_to admins_backoffice_subject_path(subject),method: :delete, class:"btn btn-danger btn-circle", data: { confirm: t('messages.confirm_with', item: subject.description.truncate(15))} do %>
                        <i class="fa fa-minus"></i>
                    <% end %>


                </td>
            </tr>
        <% end%>
    </tbody>
   
</table>

<div class="text-center"> 
    <%=  paginate @subjects%>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: { action_message: 'Novo' }%>

app/views/admins_backoffice/welcome/index.html.erb
<h1>AdminsBackoffice::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>


<p><%= link_to "Fazer Logoff [#{current_admin.email}]", destroy_admin_session_path, method: :delete%></p>

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>


<% if user_signed_in? %>
    <p>Usuario Logado</p>
<% else %>
    <p>Usuario não logado</p>
<% end%>



<% if admin_signed_in? %>
    <p>Admin Logado</p>
<% else %>
    <p>Admin não logado</p>
<% end%>